fragment OntologyEntryFields on OntologyNodeInterface {
    id
    versionId
    view

    phase

    name
    description
    ... on Term {
        subjects { id versionId view name }
        scales { id versionId view name }
        categories { id versionId view name }
        observationMethods { id versionId view name }
        traits { id versionId view name }
        variables { id versionId view name }
        controlMethods { id versionId view name }
        conditions { id versionId view name }
        factors { id versionId view name }
        events { id versionId view name }
        locationTypes { id versionId view name }
        layoutTypes { id versionId view name }
        designs { id versionId view name }
        roles { id versionId view name }
        titles { id versionId view name }
    }
    ... on OntologyRelationships {
        parents { id versionId view name }
        children { id versionId view name }
    }
    ... on RelatedToTerms { terms { id versionId view name } }
    ... on Subject {
        traits { id versionId view name }
        conditions { id versionId view name }
    }
    ... on Trait {
        subjects { id versionId view name }
        variables { id versionId view name }
    }
    ... on Condition {
        subjects { id versionId view name }
        factors { id versionId view name }
    }
    ... on Scale {
        scaleType
        categories  { id versionId view name }
        variables { id versionId view name }
        factors { id versionId view name }
    }
    ... on Category { scales  { id versionId view name } }
    ... on ObservationMethod {
        observationType
        variables  { id versionId view name }
    }
    ... on Variable {
        trait { id versionId view name }
        observationMethod { id versionId view name }
        scale  {
            id versionId view name
            scaleType
            categories { id versionId view name }
        }
    }
    ... on ControlMethod { controlType factors { id versionId view name } }
    ... on Factor {
        condition { id versionId view name }
        controlMethod { id versionId view name }
        scale {
            id versionId view name
            scaleType
            categories { id versionId view name } } }
    ... on Event {
        variables { id versionId view name }
        factors { id versionId view name }
    }
    ... on LayoutType { axes }
}