query organisations {
    organisations{
        status
        result {
            id
            name
            fullname
            children { id }
            affiliations {
                read { user { id name fullname } authorisation heritable }
                write { user { id name fullname } authorisation heritable }
                admin { user { id name fullname } authorisation heritable }
                curate { user { id name fullname } authorisation heritable }
            }
            inheritedAffiliations {
                read { user { id name fullname } authorisation heritable }
                write { user { id name fullname } authorisation heritable }
                admin { user { id name fullname } authorisation heritable }
                curate { user { id name fullname } authorisation heritable }
            }
            directAffiliations {
                read { user { id name fullname } authorisation heritable }
                write { user { id name fullname } authorisation heritable }
                admin { user { id name fullname } authorisation heritable }
                curate { user { id name fullname } authorisation heritable }
            }
        }
        errors {
            message
        }
    }
}