query organisationsTeams($teamIds: [ID!]) {
    organisationsTeams(ids: $teamIds){
        status
        result {
            id
            name
            fullname
            parent { id }
            children { id }
            affiliations {
                read { user { id name fullname } authorisation heritable }
                write { user { id name fullname } authorisation heritable }
                admin { user { id name fullname } authorisation heritable }
                curate { user { id name fullname } authorisation heritable }
            }
        }
        errors {
            message
        }
    }
}