#import "./recordFragment.graphql"
query Datasets($datasetIds: [ID!], $studyIds: [ID!], $conceptIds: [ID!]) {
  datasets(ids: $datasetIds, studyIds: $studyIds, conceptIds: $conceptIds) {
    status
    result {
      id
      concept {
        id versionId view
        name
        ... on Variable {
          scale {
            id versionId view
            name
            scaleType
            categories {
              id
              name
            }
          }
        }
        ... on Factor {
          scale {
            id versionId view
            name
            scaleType
            categories {
              id
              name
            }
          }
        }
      }
      records {
        ...RecordFields
      }
      contributors {
        id
        name
      }
      references {
        id
      }
    }
    errors {
      name
      message
    }
  }
}